#
# The Firefly III Data Importer will ask you for the Firefly III URL
# and a "Client ID". You can generate the Client ID at
# http://localhost/profile (after registering) The Firefly III URL is:
# http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:

  app:
    image: fireflyiii/core:latest
    hostname: firefly-iii-app
    container_name: batesste-firefly-iii-core
    networks:
      - batesste-firefly-iii
    restart: always
    volumes:
      - batesste-firefly-iii-upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '1080:8080'
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: firefly-iii-db
    container_name: batesste-firefly-iii-db
    networks:
      - batesste-firefly-iii
    restart: always
    env_file: .db.env
    volumes:
      - batesste-firefly-iii-db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: firefly-iii-importer
    container_name: batesste-firefly-iii-importer
    restart: always
    networks:
      - batesste-firefly-iii
    ports:
      - '1081:8080'
    depends_on:
      - app
    env_file: .importer.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as
    # an environment variable and replace REPLACEME below. The
    # STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine:latest
    container_name: batesste-firefly-iii-cron
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly-iii-app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - batesste-firefly-iii

  backup:
    image: offen/docker-volume-backup:latest
    hostname: firefly-iii-backup
    container_name: batesste-firefly-iii-backup
    restart: always
    env_file:
      - .backup.env
      - .aws.creds.env
    volumes:
      - batesste-firefly-iii-upload:/backup/upload-backup:ro
      - batesste-firefly-iii-db:/backup/db-backup:ro
    depends_on:
      - app
    networks:
      - batesste-firefly-iii

volumes:
  batesste-firefly-iii-upload:
    external: true
    name: batesste-firefly-iii-upload
  batesste-firefly-iii-db:
    external: true
    name: batesste-firefly-iii-db

networks:
  batesste-firefly-iii:
    driver: bridge
